### ISSUE TITLE
Automated testing before integration

### ISSUE THREAD

**Issue by JimmyCIsCrazySee** [cs481-ekh/f22-dust-devils#20]
As a developer, I need to setup automated testing, so I can automatically test features before integration to the main branch

## Definition of Done
- [x] Testing framework is incorporated
- [x] Automated testing works on Ubuntu OS
- [x] Automated testing works on MAC OS
- [x] Automated testing works on Windows OS

## Tasks
- [x] #31 
- [x] #32 
- [x] #28 
- [x] #35 
- [x] #37 
- [x] #38
