### ISSUE TITLE
Test 2 - Temperature Time Series

### ISSUE THREAD

**Issue by JimmyCIsCrazySee** [cs481-ekh/f22-dust-devils#22]
As a developer, I want to provide a series of unit tests for temperature time series, so that I can provide an exhaustive proof of function 

## Definition of Done
- [x] TTS function returns output
- [ ] Output is accurate
- [ ] Output is consistent
- [ ] TTS function contains dependable error handling

## Tasks
- [ ] Task 1: #45 
- [ ] Task 2: Fix all errors in TTS so that the team can compile and run with no issues
- [ ] Task 3: Build unit tests to ensure quality data is returned from our TTS

**Comment by JimmyCIsCrazySee** [comment]
Perception of project changed; this story/task redundant and therefore no longer necessary.
