### ISSUE TITLE
PDS4 Module Integration

### ISSUE THREAD

**Issue by JimmyCIsCrazySee** [cs481-ekh/f22-dust-devils#23]
As a user, I would like to allow the easy read-in of NASA data and metadata into the project

## Definition of Done
- [ ] Supports latest version/format of PDS4 files
- [x] PDS4 Tools library is fully integrated into project (i.e., every relevant .py file in project includes the library)

## Tasks
- [x] Include pip install for PDS tools into build.sh
- [x] Download and import PDS4 module/libraries
- [ ] Import/integrate PDS4-reading capabilities to driver files in Muldoon
- [x] #46

**Comment by senamihodonu** [comment]
User story is redundant. Replaced by #55
