### ISSUE TITLE
Make Package Object Oriented

### ISSUE THREAD

**Issue by samfarmer1** [cs481-ekh/f22-dust-devils#29]
As a developer, I would like to have my project to have an object oriented setup, so that when I have to make changes or read through the code, classes are easier to use.

## Definition of Done
- [x] Functional MetTimeseries class
- [x] Functional PressureTimeseries class
- [x] Functional TemperatureTimeseries  class
- [x] Functional read_data implementation

## Tasks 
- [x] #79
- [x] #80
- [x] #81
- [x] #114 
- [x] #115 
- [x] #116

**Comment by senamihodonu** [comment]
Work Session 12:30 - 1:20
- Worked on Using_Muldoon tasks
