### ISSUE TITLE
Setup for project development

### ISSUE THREAD

**Issue by samfarmer1** [cs481-ekh/f22-dust-devils#5]
---
name: Setup for project development
about: Aims to setup the Muldoon development environment.
title: 'user: Setup for project development'
labels: story
assignees: Jim, Senami, Samantha, Lukas

---

As a developer, I want to have a testing framwork, linter, and source code, so that I can develop the Muldoon Python package efficiently.

## Definition of Done
- [x] As a developer, I can run Pytest in the command line and all of my unit tests will run and output if they pass or fail.
- [x] As a developer, I know how to structure any new tasks on github.
- [x] As a developer I know how to structure any new stories on github.
- [x] As a developmer I know how much space and proper indentation when I write a new class.
- [x] As a developer, I have access to all of the Muldoon source code and can compile the package after alteratiing the package.

## Tasks
- [x] #4
- [x] #6
- [x] #3
