### ISSUE TITLE
Muldoon Instructional Webpage

### ISSUE THREAD

**Issue by senamihodonu** [cs481-ekh/f22-dust-devils#53]
As a user, I want to access a webpage, so that I can learn how to use the Muldoon package

## Definition of Done
- [x] Display local webpage with how to run the Muldoon package
- [x] Webpage displays Matplotlib graphs to show examples of the expected output

## Tasks
- [x] #61 
- [x] Get dummy webpage with not data
- [x] On webpage, display text explaining what Muldoon is/how it works
- [x] Tangible graphs to represent data is displayed

**Comment by lukaskarlsson290** [comment]
I've been working on updates to this over the week. I'm implementing Jupyter notebook usage as well as adding in API usage

**Comment by lukaskarlsson290** [comment]
Reworked the webpage to show how Jupyter Notebooks and the API works, as well as links to the usage of the two
