### ISSUE TITLE
Modify/Implement functions to process PSD4 files

### ISSUE THREAD

**Issue by senamihodonu** [cs481-ekh/f22-dust-devils#55]
As a user, given a PSD4 data, I want to be able to obtain relevant data, so that I can model different time-series.

## Definition of Done
- [x] Program is capable of calling PSD command through, e.g., subprocess calls, on a given file
- [x] Tested time/pressure read function
- [x] Tested time/temperature read function

## Tasks
- [x] Research and understand the requirements for PSD to "understand" and process a numpy file
- [x] #63 
- [x] #66 
- [x] #67 
- [x] Research methods to add to read_pds4_data.py to ensure PDS4 readability
- [x] #82
- [x] #83
- [x] #86 
- [x] #89
- [x] #101 
- [x] #87 
- [x] #88

**Comment by senamihodonu** [comment]
10/15/2022
- Worked from 2pm - 6:30pm on the read_data.py file.
  - Had a peer programming session with Jim Crowell
  - Several tasks are close to completion
