### ISSUE TITLE
Refactor PressureTimeseries into a class of its own

### ISSUE THREAD

**Issue by senamihodonu** [cs481-ekh/f22-dust-devils#80]
## Definition of Done
- [ ] Pressure Time Series functions and methods are moved into their own .py file
- [ ] New .py file has appropriate importations and dependencies covered
- [ ] New .py file can be submitted to the git without negatively affecting .yml tests

## Tasks
- [ ] Relocate PTS methods to new file
- [ ] Upload and confirm validity of changes

**Comment by JimmyCIsCrazySee** [comment]
10/13 2PM - Added DoD and Tasks to Story

**Comment by JimmyCIsCrazySee** [comment]
10/16 2PM - Researching Pandas/PDS4 intercompatibility, PDS4/XML labeling

PDS4-Tools has a label query function?
Fork program on csv v xml?

**Comment by senamihodonu** [comment]
User story is adds unnecessary complexity to the project and is deemed unnecessary
