### ISSUE TITLE
Implement function to read time/pressure data from  PDS4 label

### ISSUE THREAD

**Issue by senamihodonu** [cs481-ekh/f22-dust-devils#82]
As a user, given a csv file with time and pressure data, I want to be able to process it using PDS4-tools in Python to meaningfully make use of the data and produce an output

## Definition of Done
- [x] Program can successfully call PDS4-tools functions on a file which contains PDS4 labeling
- [x] Program is capable of processing csv files into PDS4-labeled files 
OR
- [x] Developers are capable of modifying extant data files with appropriate labeling such that PDS4-tools becomes applicable

## Tasks
- [x] Research into PDS4 labeling
- [x] Understand what, if anything, needs to be added to csv files in project in order to process
- [x] #88
- [x] #96

**Comment by JimmyCIsCrazySee** [comment]
10/13 - 2PM: Added DoD and Tasks list to Story

**Comment by JimmyCIsCrazySee** [comment]
10/16 2PM - Researching Pandas/PDS4 intercompatibility, PDS4/XML labeling

PDS4-Tools has a label query function?
Fork program on csv v xml?

**Comment by JimmyCIsCrazySee** [comment]
10/15 3PM - Modifying read_data.py to include PDS4 function/CSV fork

**Comment by JimmyCIsCrazySee** [comment]
10/15 520PM - read_data.py is successfully reading PDS4 files
