### ISSUE TITLE
user: Muldoon API - Python fast-api

### ISSUE THREAD

**Issue by lukaskarlsson290** [cs481-ekh/f22-dust-devils#92]
As a user, I want to be able to read files through an API, so that I can process and display graphs with minimal coding

## Definition of Done
- [x] API call to Mars pds website returns data
- [x] Graphs are displayed in local browser to user
- [x] Implementation is ready for demonstration

## Tasks
- [x] API returns data on call
- [x] Implement Pressure Timeseries through API calls
- [x] Implement ATS data through API calls
- [ ] Error handling that is useful to user if data is unable to be returned
- [x] Add options for different graph displays (i.e. implement the various options in UsingMuldoon example)
- [x] Code is refactored/cleaned up

**Comment by lukaskarlsson290** [comment]
Spent a couple hours implementing fast-api in local test area
Able to return data from Mars website that we pull CSV's from
This implements a layer of abstraction for a user and removes the need to enter filenames/download files locally
Next steps:
Show team what has been done
Take in suggestions on improvements/see if we would like to continue with this implementation as an overarching goal

**Comment by lukaskarlsson290** [comment]
Added options for PS, ATS, or both to be represented to the user locally. Users are able to pick this by adding in options to the search bar

**Comment by lukaskarlsson290** [comment]
Spent about an hour researching how to speed up the API. Works fast for generating one graph, there are ways to speed up matplotlib calls when you combine the output of two functions (i.e. PS AND ATS data). Overall, it works fairly quickly, would like to see if there are improvement speeds once the project is refactored/cleaned up

Next steps will be to allow users to see any/every graph possible and give different layout options (if that functionality is available with this api)

It seems that the import statements will have to stay for now. We talked about trying to clean these up but I'm unable to find a clean-cut solution to this

**Comment by lukaskarlsson290** [comment]
Something that's important I would like to add is usage information and error handling. The API itself is not specific when no data is returned, making it confusing as a user. I know how to display this message; it'll involve refactoring what I have so far in order for the message to be cleared. 
This is because the file path data is not consistent on the website. It's close, but it doesn't always match (for example, there could be a 2 rather than a 1 at the end of the filename, which is usually the case) so I will need to implement a way to verify that a file path is incorrect. The nice thing about using requests is that it returns codes internally that can be displayed (404 errors, etc)

**Comment by lukaskarlsson290** [comment]
Implemented all but one function found on the Analyzing Mars Jupyter Notebook. This is centered around pressure, but the functions would be easily adaptable to the rest of the data we are working with. My next steps will be to clean up the code and refactor it for speed increases and for the sponsor to better understand. The DOD has been updated to reflect this

**Comment by lukaskarlsson290** [comment]
Most of the functions we have as examples are implemented. I separated my functions from the api calls themselves to clean up the code and make it easier to read. I put everything into one folder under the muldoon directory with a txt file for usage of the api
